### ISSUE TITLE
Special/Dynamic clearance levels

### ISSUE THREAD

**Issue by Startouf** [matiasgagliano/action_access#2]
Considering the following models

```ruby
class User
  has_and_belongs_to_many :articles

  belongs_to :role
  def clearance_level
    role.name
  end

class Article
  has_and_belongs_to_many :authors, class_name: 'User'
```

(I originally had a simple `has_many :articles` and `belongs_to :user` in mind, but it's more interesting with n-to-n)

I want to only let Users edit their own articles. I need to define a "dynamic" clearance level so only Users that are the authors of a given article can access the [:edit, :destroy] actions. How would I do that ? I would have thought of some syntax like

```ruby
class User
  def clearance_level_for_article(article)
    article.in?(self.articles) ? :author : :none
  end
```

And in the controller

```ruby
class ArticlesController
  before_action :find_article
  let :all, [:index, :show]
  let :authors, [:edit, :destroy]

  def current_clearance_level
    # For :edit and :destroy actions only
    current_user.clearance_level_for_article(@article)
    # For the rest :
    super
  end
```

The problem is that the `current_clearance_level` also becomes action specific. Way around this ?

**Comment by matiasgagliano** [comment]
Please read the [CONTRIBUTING file](https://github.com/matiasgagliano/action_access/blob/master/CONTRIBUTING.md) and avoid posting questions on the issue tracker. If you need assistance use one of the means listed there.

To point you in the right direction regarding the question, ActionAccess controls access at controller level (by action) and what you describe is restricting access based on an intrinsic characteristic of a record (the association to the article), closer to model level.

The [Fine Grained Access Control](https://github.com/matiasgagliano/action_access#fine-grained-access-control) section in the docs describes how to address this.

You have to allow every *author* (or user) to access the *edit* and *destroy* actions, check within the action if the current author is allowed to edit the particular article and restrict access with `not_authorized!` if not.

```ruby
class ArticlesController
  let :all, [:index, :show]
  let :authors, [:edit, :destroy]
  before_action :set_article

  def edit
     not_authorized! unless @article.in? current_user.articles
     # ...
  end

end
```

That should do the trick.
