### ISSUE TITLE
Compatibility with Rails 5

### ISSUE THREAD

**Issue by ZempTime** [matiasgagliano/action_access#7]
Hey, love this gem. Authentication should absolutely happen in controllers, and your syntax for it is brilliant.

Will you be supporting it into Rails 5? Tried to drop this in but got:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0.rc1)

  In Gemfile:
    rails (~> 5.0.0.rc1)

    action_access (~> 0.1.0) was resolved to 0.1.0, which depends on
      rails (~> 4.1)
```

Anyway, even if there's no plan for it in the time being, I might just reimplement it manually over the short term!

**Comment by matiasgali** [comment]
Made a small cleanup and added Rails 5 support :tada: 

Thanks for supporting [ActionAccess](https://github.com/matiasgagliano/action_access), enjoy!
